M48
; DRILL file {KiCad 9.0.0} date 2025-03-10T21:20:02+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-10T21:20:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.400
%
G90
G05
T1
X183.14Y-70.98
X186.14Y-70.98
T2
X155.81Y-67.64
T3
X170.39Y-77.16
X177.17Y-113.15
X190.71Y-67.62
M30
